<?php
//The actual order
class Order
{
    private $orderId;//Auto generated by the database
    private $personId; //id of the person
    private $orderDate;//Today's date
    private $orderedItems; //an array of type OrderItem containg each ordered cheese and its details such as weight and price
    private $shippingAddress; //where is it going


    function __get($attribute)
    {
        return $this->$attribute;
        
    }
    function __set($attribute, $value)
    {
        $this->$attribute = $value;

    }
    function setDetails($personId, $date, $items, $address)
    {
        $this->personId = $personId;
        $this->orderDate = $date;
        $this->orderedItems = $items;
        $this->shippingAddress = $address;

    }
}